# Build Photino.Native project from debug branch in GitHub
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
    - debug

variables:
    versionprefix: 0.9.0
    buildConfiguration: "Release"

jobs:
    - job: "Build_Win_x64"
      pool:
          name: "SelfHostedPool"
          vmImage: "windows-latest"

      steps:
          #- script: choco install windows-sdk-10-version-2004-windbg
          #- script: choco install windows-sdk-10.1 #--version=10.0.22621.0
          
          - task: NuGetCommand@2
            displayName: "NuGet package restore for Windows (x64)"
            inputs:
                command: "restore"
                restoreSolution: "Photino.Native.sln"
                feedsToUse: "select"

          - task: VSBuild@1
            displayName: "Build Windows (x64) native assets"
            inputs:
                solution: "Photino.Native.sln"
                platform: "x64"
                msbuildArchitecture: "x64"
                configuration: "$(buildConfiguration)"


