using XarChat.FList2.FList2Api.Implementation.Firehose.Messages;

namespace XarChat.FList2.FList2Api.Implementation.Firehose.Messages.Incoming
{
    /// <summary>
    /// A message to indicate the continuity of the firehose stream has been
    /// broken, and the client should proactively retrieve the current state
    /// of its tracked entities.
    /// </summary>
    /// <remarks>
    /// This message is not actually received over the firehose socket, it
    /// is synthentically generated by the FirehoseManager when it has to
    /// recycle the STOMP websocket and is unable to resume an existing
    /// session.
    /// </remarks>
    public class FirehoseBrokenMessage : IFirehoseIncomingMessage
    {
    }
}
